times=('Palmeiras','Santos','Flamengo','Atlético','Internacional','Athletico-PR','Botafogo','Goiás','Corinthians','São Paulo','Grêmio','Bahia','Ceará SC','Fortaleza','Vasco da gama','Cruzeiro','Fluminense','Chapecoense','CSA','Avaí')
print('-=' * 15)
print(f'Lista de Times do Brasileirão: {times}')
print('-=' * 15)
print(f'Os 5 Primeiros times são: {times[0:5]}')
print('-=' * 15)
print(f'Os ùltimos 4 times são: {times[-4:]}')
print('-=' * 15)
print(f'Times em ordem alfabética: {sorted(times)}')
print('-=' * 15)
print(f'O Chapecoense está na {times.index("Chapecoense")+1} posição ')