n = int(input('Insira um Numero: '))
print('Valor Multiplicado por 1: {}'.format(n * 1))
print('Valor Multiplicado por 2: {}'.format(n * 2))
print('Valor Multiplicado por 3: {}'.format(n * 3))
print('Valor Multiplicado por 4: {}'.format(n * 4))
print('Valor Multiplicado por 5: {}'.format(n * 5))
print('Valor Multiplicado por 6: {}'.format(n * 6))
print('Valor Multiplicado por 7: {}'.format(n * 7))
print('Valor Multiplicado por 8: {}'.format(n * 8))
print('Valor Multiplicado por 9: {}'.format(n * 9))